#basic options
title:  Security for All
author:  Zoe Braiterman
email:  your.email@domain.com
description:  A wonderful site
twitter_username:  zbraiterman
github_username:  zbraiterman

# Build settings
markdown:  kramdown
theme:  minima
