#basic options
title:  Diversecurity
author:  Zoe Braiterman
description:  Security for All
twitter_username:  zbraiterman
github_username:  zbraiterman

# Build settings
markdown:  kramdown
theme:  minima
